version: '3.8'

services:
  sra-app:
    build: .
    container_name: systematic_review_agent
    ports:
      - "8000:8000"
    volumes:
      # Persiste os uploads e resultados localmente
      - ./uploads:/app/uploads
    environment:
      # Fallback caso variáveis sejam passadas diretamente do host
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
